repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-added-large-files
    -   id: detect-private-key

-   repo: local
    hooks:
    -   id: dart-format
        name: dart format
        entry: dart format --set-exit-if-changed app
        language: system
        files: \.dart$
        pass_filenames: false
    -   id: flutter-analyze
        name: flutter analyze
        entry: bash -c "cd app && flutter analyze"
        language: system
        files: \.dart$
        pass_filenames: false
